name: Build and test package

on: [push]

jobs:
  build:

    name: Test with ${{matrix.python}} on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: |
          pip install nox poetry

      - name: Run tests with Nox
        run: nox -s lint tests
